tap 'homebrew/cask'
tap 'tilfin/aws'

brew 'anyenv'
brew 'awscli'
brew 'ansible'
brew 'direnv'
brew 'fish'
brew 'yarn'
brew 'vim'

# 'tilfin/aws'
brew 'swrole'

# cask
cask 'karabiner-elements'
# cask 'slack'
# cask 'google-chrome'
# cask 'alfred'
# cask 'vscode'
# cask 'notion'
# cask 'sequel-pro-beta'
# cask 'iterm2'
# cask 'postman'
# cask 'macdown'
# cask 'krisp'
# cask 'deepl'
# cask 'dbeaver'
# cask 'quiver'
# cask 'divvy'
# cask '1password'
